; ScanBot3000 firmware — PlatformIO configuration

[platformio]
src_dir = ${PROJECT_DIR}/src/${PIOENV}
default_envs = esp32s3_Anna

[env]
lib_ldf_mode = chain+

[env:esp32s3_Anna]
platform = espressif32 @ ^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -D ARDUINO_USB_MODE=1 -D ARDUINO_USB_CDC_ON_BOOT=1 -DESP32 -DARDUINO_ARCH_ESP32
board_build.flash_size = 16MB
board_build.psram = enabled
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    Wire
    SPI
    adafruit/Adafruit NeoPixel
    thomasfredericks/Bounce2
    waspinator/AccelStepper@^1.64
    robtillaart/AS5600@^0.6.6
    adafruit/Adafruit GFX Library@^1.12.1
    milesburton/DallasTemperature@^4.0.4
    adafruit/Adafruit SSD1306@^2.5.15
    janelia-arduino/TMC2209@^10.1.0
    adafruit/Adafruit BusIO@^1.17.4
    adafruit/Adafruit_VL6180X
    paulstoffregen/OneWire@^2.3.8

[env:teensy41_Beata]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
build_flags = -D USB_SERIAL
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BusIO@^1.17.4
    paulstoffregen/OneWire@^2.3.8
